---
title: "Publications & Presentations"
editor: visual
---


::: {.callout-note}
## Links

>- **Google Scholar**: <https://scholar.google.com/citations?user=KyNSuUAAAAAJ&hl=en>
>- **ORCID**: <https://orcid.org/0000-0002-2011-7535>
:::

&emsp;

## Articles

-   Chen F, Hu Z, Li Q, Zheng X, Li M, Salcher-Konrad M, Comas-Herrera A, Knapp M, Shi C; STRiDE consortium. Effectiveness of Interventions to Support Carers of People With Dementia in Low- and Middle-Income Countries: A Systematic Review and Meta-Analysis. Int J Geriatr Psychiatry. 2025 Mar;40(3):e70054. doi: 10.1002/gps.70054. PMID: 40015952; PMCID: PMC11867927.
    [Full text](https://pmc.ncbi.nlm.nih.gov/articles/PMC11867927/){target=_blank} ·
    [PDF](resources/GPS-40-e70054.pdf){target=_blank}

## Presentation

-   Hu Z, Han C, Polychronopoulou E, Raji M, Kuo F (2025) Mediators associated with Racial Disparities in Hospice Use During the Last Six Months of Life. Gerontological Society of America (GSA) 2025 Annual Scientific Meeting, November 2025, Boston MA
-   Han C, Downer B, Hu Z, Wong R (2025) Expanded Education, Better Health in Later Life? –Evidence from the Mexican Health and Aging Study (MHAS). Gerontological Society of America (GSA) 2025 Annual Scientific Meeting, November 2025, Boston MA
-   Han C, Downer B, Hu Z, Wong R (2025) Cross-National Comparison of Hearing Status, Social Activities, and Verbal Memory: United States, Mexico and China . Gerontological Society of America (GSA) 2025 Annual Scientific Meeting, November 2025, Boston MA
-   Han C, Downer B, Hu Z, Wong R (2025) Cross-National Comparison of Hearing Status and Verbal Function in the United States, Mexico, and China: Gender and Urban-Rural Disparities. Population Associate of America (PAA) Annual Meeting, April 2025, Washington DC
